//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `Monitor.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <Monitor.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <Ice/LocalException.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 3
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::IceInternal::DefaultUserExceptionFactoryInit<::RoboCompMonitor::HardwareFailedException> iceC_RoboCompMonitor_HardwareFailedException_init("::RoboCompMonitor::HardwareFailedException");

const ::std::string iceC_RoboCompMonitor_Monitor_ids[2] =
{
    "::Ice::Object",
    "::RoboCompMonitor::Monitor"
};
const ::std::string iceC_RoboCompMonitor_Monitor_ops[] =
{
    "getState",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};
const ::std::string iceC_RoboCompMonitor_Monitor_getState_name = "getState";

}

RoboCompMonitor::HardwareFailedException::~HardwareFailedException()
{
}

const ::std::string&
RoboCompMonitor::HardwareFailedException::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompMonitor::HardwareFailedException";
    return typeId;
}

bool
RoboCompMonitor::Monitor::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompMonitor_Monitor_ids, iceC_RoboCompMonitor_Monitor_ids + 2, s);
}

::std::vector<::std::string>
RoboCompMonitor::Monitor::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_RoboCompMonitor_Monitor_ids[0], &iceC_RoboCompMonitor_Monitor_ids[2]);
}

::std::string
RoboCompMonitor::Monitor::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompMonitor::Monitor::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompMonitor::Monitor";
    return typeId;
}

/// \cond INTERNAL
bool
RoboCompMonitor::Monitor::_iceD_getState(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    MonitorStates ret = this->getState(current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompMonitor::Monitor::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompMonitor_Monitor_ops, iceC_RoboCompMonitor_Monitor_ops + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompMonitor_Monitor_ops)
    {
        case 0:
        {
            return _iceD_getState(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
RoboCompMonitor::MonitorPrx::_iceI_getState(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::RoboCompMonitor::MonitorStates>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompMonitor_Monitor_getState_name);
    outAsync->invoke(iceC_RoboCompMonitor_Monitor_getState_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        [](const ::Ice::UserException& ex)
        {
            try
            {
                ex.ice_throw();
            }
            catch(const HardwareFailedException&)
            {
                throw;
            }
            catch(const ::Ice::UserException&)
            {
            }
        });
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
RoboCompMonitor::MonitorPrx::_newInstance() const
{
    return ::IceInternal::createProxy<MonitorPrx>();
}
/// \endcond

const ::std::string&
RoboCompMonitor::MonitorPrx::ice_staticId()
{
    return Monitor::ice_staticId();
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_RoboCompMonitor_Monitor_getState_name = "getState";

}

namespace
{

const ::IceInternal::DefaultUserExceptionFactoryInit< ::RoboCompMonitor::HardwareFailedException> iceC_RoboCompMonitor_HardwareFailedException_init("::RoboCompMonitor::HardwareFailedException");

}

RoboCompMonitor::HardwareFailedException::HardwareFailedException(const ::std::string& what) :
    ::Ice::UserException(),
    what(what)
{
}

RoboCompMonitor::HardwareFailedException::~HardwareFailedException() throw()
{
}

::std::string
RoboCompMonitor::HardwareFailedException::ice_id() const
{
    return "::RoboCompMonitor::HardwareFailedException";
}

RoboCompMonitor::HardwareFailedException*
RoboCompMonitor::HardwareFailedException::ice_clone() const
{
    return new HardwareFailedException(*this);
}

void
RoboCompMonitor::HardwareFailedException::ice_throw() const
{
    throw *this;
}

/// \cond STREAM
void
RoboCompMonitor::HardwareFailedException::_writeImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice("::RoboCompMonitor::HardwareFailedException", -1, true);
    ::Ice::StreamWriter< HardwareFailedException, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompMonitor::HardwareFailedException::_readImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< HardwareFailedException, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::RoboCompMonitor::upCast(Monitor* p) { return p; }

void
::IceProxy::RoboCompMonitor::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< Monitor>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new Monitor;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::RoboCompMonitor::Monitor::_iceI_begin_getState(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompMonitor_Monitor_getState_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompMonitor_Monitor_getState_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompMonitor_Monitor_getState_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_RoboCompMonitor_Monitor_getState_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::RoboCompMonitor::MonitorStates
IceProxy::RoboCompMonitor::Monitor::end_getState(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompMonitor_Monitor_getState_name);
    ::RoboCompMonitor::MonitorStates ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::RoboCompMonitor::HardwareFailedException&)
        {
            throw;
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::RoboCompMonitor::Monitor::_newInstance() const
{
    return new Monitor;
}
/// \endcond

const ::std::string&
IceProxy::RoboCompMonitor::Monitor::ice_staticId()
{
    return ::RoboCompMonitor::Monitor::ice_staticId();
}

RoboCompMonitor::Monitor::~Monitor()
{
}

/// \cond INTERNAL
::Ice::Object* RoboCompMonitor::upCast(Monitor* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_RoboCompMonitor_Monitor_ids[2] =
{
    "::Ice::Object",
    "::RoboCompMonitor::Monitor"
};

}

bool
RoboCompMonitor::Monitor::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompMonitor_Monitor_ids, iceC_RoboCompMonitor_Monitor_ids + 2, s);
}

::std::vector< ::std::string>
RoboCompMonitor::Monitor::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_RoboCompMonitor_Monitor_ids[0], &iceC_RoboCompMonitor_Monitor_ids[2]);
}

const ::std::string&
RoboCompMonitor::Monitor::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompMonitor::Monitor::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompMonitor::Monitor";
    return typeId;
#else
    return iceC_RoboCompMonitor_Monitor_ids[1];
#endif
}

/// \cond INTERNAL
bool
RoboCompMonitor::Monitor::_iceD_getState(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    MonitorStates ret = this->getState(current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_RoboCompMonitor_Monitor_all[] =
{
    "getState",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

/// \cond INTERNAL
bool
RoboCompMonitor::Monitor::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompMonitor_Monitor_all, iceC_RoboCompMonitor_Monitor_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompMonitor_Monitor_all)
    {
        case 0:
        {
            return _iceD_getState(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
RoboCompMonitor::Monitor::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< Monitor, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompMonitor::Monitor::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< Monitor, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
RoboCompMonitor::_icePatchObjectPtr(MonitorPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = MonitorPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(Monitor::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
